### PR TITLE
Add 3-body invariant mass

### PR DESCRIPTION
**Pull request by jheikkil**
Based on the macros code from @arnobaer  - thanks for his help! Tested using a seed with 3 muons.

I would like to understand how to deal with precision definition for the mass3 - can we use LUTS01 as I did below [1], or should this be defined differently?

[1] https://github.com/cms-l1-dpg/L1MenuTools/compare/master...jheikkil:bugFixes?expand=1#diff-812f1df4e11f882077929151bd51ec56e39dcf2f7df906a3f9efe5e24afdbc8eR296

### CODE REVIEW

**Comment by jheikkil** [comment]
Updated the LUTs as suggested by Bernhard, please merge and Anna T could test?

**Review by elfontan — COMMENTED** [review]
Thank you, Jaana, everything looks fine to me!
One question: do we need this part [1] only to include the Muon3CorrelationTemplate?
Why are we defining a combination only for 0-1? Are we taking into account the other pairs here [2]? 

[1]
https://github.com/cms-l1-dpg/L1MenuTools/pull/48/files#diff-8e68a6c321f37224294882c80e57eec49061e08994a0297941601b587269af36R298-R300

[2]
https://github.com/cms-l1-dpg/L1MenuTools/blob/fdfdf76e22392b08973e3f8c1da1ff7c067439b0/rate-estimation/menu2lib/templates/Muon3CorrelationTemplate.cc#L50-L66

**Comment by jheikkil** [comment]
>  One question: do we need this part [1] only to include the Muon3CorrelationTemplate?
Strictly speaking: no. Since we do not have 3-body invariant mass for any other objects than muons, we could just call Muon3CorrelationTemplate when the type is InvariantMass3. I think it might make sense to do this check though... Howover, if we wanted to do this well, we would also check the type of the 3rd object. 

>  Why are we defining a combination only for 0-1? Are we taking into account the other pairs here [2]?
What do you mean by only for 0-1? I would say that based on [3] we actually check all pairs? Perhaps I am misunderstanding something?

[3] https://github.com/cms-l1-dpg/L1MenuTools/blob/fdfdf76e22392b08973e3f8c1da1ff7c067439b0/rate-estimation/menu2lib/templates/Muon3CorrelationTemplate.cc#L8-L12

**Comment by elfontan** [comment]
Hey Jaana, 
I agree that it is fine to have the implementation only for muons, no problem there.
I try to explain better my doubt.
All questions were actually related: I was wondering if the fact that "combination" is set only for object 0 and object 1:
set combination = tmEventSetup.getObjectCombination(objects[0].getType(), objects[1].getType())

is due to the fact that in that part of the code we just want to include the Muon3CorrelationTemplate OR if we need to build there the three different combinations of objects: 0-1, 1-2, 0-2.
Maybe I do not completely understand what happens here [*]: "combination" is used with "permutation" in the loop to take into account all different muon pairs? It seems to me that we are redefining "combination" here: 
const auto& combination = CombinationFactory::get(candidates.size(), {{nObjects}});",
and it is not the same definition as before, where only 0-1 are considered. This is my confusion...

[*] https://github.com/cms-l1-dpg/L1MenuTools/blob/fdfdf76e22392b08973e3f8c1da1ff7c067439b0/rate-estimation/menu2lib/templates/Muon3CorrelationTemplate.cc#L50-L66

**Comment by arnobaer** [comment]
Hi Elisa,

> All questions were actually related: I was wondering if the fact that "combination" is set only for object 0 and object 1:
> set combination = tmEventSetup.getObjectCombination(objects[0].getType(), objects[1].getType())

in this case `combination` is a Jinja2 template variable holding one of the enumerations defined in utm's `esTypes` header. In this case the value `tmEventStup.MuonMuonCombination` is returned. The purpose of function `getObjectCombination` is to retrieve an enumeration value from two object types. As the are only muon type objects allowed with `InvariantMass3` the check might be removed but a workaround might be something like:

```jinja2
  {% elif cond.getType() == tmEventSetup.InvariantMass3 %}
    {% set objects = cond.getObjects() %}
    {% if objects|length == 3 and objects[0].getType() == tmEventSetup.Muon and objects[1].getType() == tmEventSetup.Muon and objects[2].getType() == tmEventSetup.Muon %}
      {% include 'Muon3CorrelationTemplate.cc' %}
    {% endif %}
  {% endif -%}
```

> const auto& combination = CombinationFactory::get(candidates.size(), {{nObjects}});",

The other `combination` variable is part of the actual c++ code of the condition and should not be confused with the template variable.

**Comment by jheikkil** [comment]
Ciao Elisa, Bernhard, 

after a private chat with Bernhard, I pushed a changed in the check for selection of the template. This should be more or less compatible with B's solution.

Thank you both! :)

**Review by elfontan — APPROVED** [review]
Thanks a lot for the work and the explanation, Jaana and Bernhard, let's proceed!

**Pull request merged**
